src/parser/validate.ts, test/parser/validate.test.ts
From: https://github.com/oclif/parser/commit/2619871f2e9c669863f32a73fa00b49d4e18d333
=> fix: accept integer 0 as valid arg input

src/config/config.ts, src/config/plugin.ts, src/config/ts-node.ts, test/helpers/init.js
~~WIP do not merge~~
This change thus introduces the idea of explicit dev mode in oclif.
This also means we are now introducing two separate bin stubs for dev & prod `bin/dev` and `bin/run`.
bin/dev:
```
#!/usr/bin/env node
process.env.NODE_ENV = 'development'
const path = require('path')
const project = path.join(__dirname, '../tsconfig.json')
require('ts-node').register({project})
require('@oclif/core').run()
.then(require('@oclif/core/flush'))
.catch(require('@oclif/core/handle'))
```
bin/run:
```
#!/usr/bin/env node
require('@oclif/core').run()
.then(require('@oclif/core/flush'))
.catch(require('@oclif/core/handle'))
```
=> fix: don't resolve lib -> src in development mode

src/help/_test-help-class.ts, src/help/index.ts, src/help/util.ts, src/index.ts, src/main.ts, test/command/helpers/test-help-in-src/src/test-help-plugin.ts, test/help/show-help.test.ts, test/help/util.test.ts
@amphro 
The help subsystem has been updated for asynchronous usage. This matches the rest of Oclif v2 runtime such that all control paths are now async for running commands, loading a help class, and displaying help. 
Why: To support ESM loading of custom help classes facilitated through ModuleLoader this is an async operation. 
Ancillary Benefit: Custom help classes can now run async operations for complex CLI implementations such as collecting runtime help information from various plugins installed. 
The updates include:
- main.ts now invokes loadHelpClass / and showHelp async.
- getHelpClass renamed to loadHelpClass matching `ModuleLoader.load` naming.
- usage of ModuleLoader to load custom help class; can now load Node modules for custom help classes.
- Help / HelpBase refactored for …
=> Help subsystem async conversion + test updates.

package.json, src/command.ts, src/config/config.ts, src/index.ts, src/main.ts, test/command/fixtures/esm/package.json, test/command/fixtures/esm/src/commands/foo/bar/fail.js, test/command/fixtures/esm/src/commands/foo/bar/succeed.js, test/command/fixtures/esm/src/commands/foo/baz.js, test/command/main-esm.test.ts, test/config/esm.test.ts
@amphro 
This rounds out ESM support for @oclif/core v2. 
ESM quality of life improvements:
- support file URL string as options input (IE 'import.meta.url').
- added `./flush.js` as an export from @oclif/core; `./src/index.ts`
- added main runtime ESM test w/ file URL as options.
- raised package.json Node engine level to `>= 12.0.0`. 
The added runtime tests focus on Main.run using a file URL as options. I also changed one of the Config ESM tests to use file URL as options as well. 
Please see the follow up message for a note about CommonJS deprecations when I raised the engine level to `>= 12.0.0`
=> ESM quality of life improvements

package.json, src/help/formatter.ts, test/help/format-command-with-options.test.ts, test/help/format-command.test.ts, test/parser/parse.test.ts, yarn.lock
This removes the extra spaces that occur between flag summaries in the `--help` output for commands.
Before:
After:
@W-9670435@
=> fix: don't put multiple newlines between flag summaries in help output

src/help/command.ts, test/help/format-command.test.ts
Adds support for multiple example commands under a single description:
```
EXAMPLES
Deploy all custom objects and Apex classes (both examples are equivalent):
$ sf deploy metadata --metadata CustomObject ApexClass
$ sf deploy metadata --metadata CustomObject --metadata ApexClass
```
@W-9719622@
=> feat: support multiple examples commands under a single description

src/help/util.ts
Updates `collateSpacedCmdIDFromArgs` so that `strict` must be explicitly set to false
[skip-validate-pr]
=> fix: update collateSpacedCmdIDFromArgs

src/help/util.ts, test/help/util.test.ts
=> fix: command name parsing when flag=value present

src/help/util.ts
`collateSpacedCmdIDFromArgs` failed to account for aliases when converting spaced commands to the normalized `commandID`. This PR fixes that.
[skip-validate-pr]
=> fix: account for aliases when converting spaced commands to commandID

src/config/config.ts, src/interfaces/config.ts, src/interfaces/hooks.ts, src/interfaces/index.ts
Improves the `Hooks` interface so that:
1. Users can extend `Hooks` to add their own hooks
2. `runHook` now expects a return type based on the `Hooks`
3. Adds a `timeout` parameter to `runHook`
4. `runHook` now returns successes and failures
```typescript
interface SfHooks extends Hooks {
'env:list': { options: {}; return: Environment[] };
'env:display': { options: {}; return: Environment };
}
export namespace SfHook {
export type EnvList = Hook<'env:list', SfHooks>;
export type EnvDisplay = Hook<'env:display', SfHooks>;
}
const hook: SfHook.EnvList = async function () {
return [
{ name: 'foo', active: true },
{ name: 'bar', active: false },
];
};
```
@W-9811480@
=> fix: improve Hooks interface

src/help/index.ts, src/main.ts
=> fix: move ctor for command help class to its own function

src/config/config.ts
Don't emit warnings when hooks fail
@W-9902043@
=> fix: don't warn on hook errors

src/config/plugin.ts, src/flags.ts, src/help/index.ts, src/main.ts, test/help/show-help.test.ts, test/parser/parse.test.ts, tsconfig.json
=> fix: adjust help text to new style guide

src/command.ts
Only print warnings when json is not enabled
=> fix: only show warnings when json is not enabled

src/command.ts, src/settings.ts
Removes the ability to enable the --json flag globally using `settings`.
Using `settings` turned out to be problematic because it's scoped to the executing plugin - in other words, if it's not set at the CLI level, it won't be set at the plugin level. Practically speaking, this is an issue when running `oclif manifest` to generate the manifest since `oclif`'s `settings` will be used in place of the plugin's - meaning that the `--json` flag won't show up in the manifest
For now, I'd like to remove this entirely and wait for users to request the feature. If there's enough demand for it, we can figure out a better way to enable flags globally
@W-9831737@
=> fix: remove ability to enable json flag globally

src/config/plugin.ts, src/config/util.ts
Pushes changes from @oclif/config upstream 
https://github.com/oclif/config/pull/289#issuecomment-984797669
=> chore(sync): push @oclif/config dependency resolution changes upstream

README.md
Noticed this while migrating to @oclif/core from @oclif/command.
=> Add missing await to README.md

src/errors/errors/cli.ts
Use `import` syntax in `errors/cli.ts`
fixes #274
=> fix: update imports in errors/cli.ts

.circleci/config.yml, test/integration/sf.e2e.ts, test/integration/util.ts
Re-enables integration tests that were temporarily disabled as we debugged the plugin install issue (#340)
=> chore: reenable integration tests

src/config/config.ts, src/config/plugin.ts, src/interfaces/hooks.ts
- Fixes module resolution for linked plugins
- Fixes issue with `command_not_found` hook always throwing an error - even if the correct command was run by `plugin-not-found`
@W-10501665@
=> fix: module resolution of linked plugins

src/cli-ux/prompt.ts, src/interfaces/hooks.ts, src/interfaces/index.ts, src/interfaces/s3-manifest.ts
Adds `S3Manifest` interface which will be used by [oclif](https://github.com/oclif/oclif/blob/main/src/tarballs/config.ts#L33) and [plugin-update](https://github.com/oclif/plugin-update/blob/main/src/update.ts#L4).
The main motivation for doing this is so that plugin-update doesn't have to depend on oclif - which should reduce it's size considerably
=> feat: add S3Manifest

src/parser/parse.ts
I believe that this addresses issue https://github.com/oclif/core/issues/330
Under test, the `process.stdin.isTTY` property isn't properly inherited (possibly related to this: https://stackoverflow.com/a/68260765) meaning that rather than bailing out immediately, the `readStdin` function hangs indefinitely waiting for input to be provided.
=> Fix: Command parsing hangs under unit test

src/util.ts
`isProd` returns false if `process.env.NODE_ENV` is either `development` or `test`
Fixes #367
=> fix: update isProd utility

src/parser/parse.ts, test/parser/parse.test.ts
fixed a bug where parsing the default worked only when the flag was of type string
This does not resolve the help issue when the flag type is not a string-friendly type (ex: a class or an object)
=> fix: parsing the default is wrong types

src/command.ts
Makes it so that global flags are settable. This allows users to have a base command class that defines flags that should be inherited by all child instances.
```typescript
export abstract class MyBaseCommand extends Command {
public static globalFlags = {
interactive: Flags.boolean({
description: 'Interactive Command Completion',
default: false,
helpGroup: 'GLOBAL',
}),
};
}
```
This was possible before but it required a lot of unpleasant code:
```typescript
export abstract class MyBaseCommand extends Command {
private static specialFlags = {
interactive: Flags.boolean({
description: 'Interactive Command Completion',
default: false,
helpGroup: 'GLOBAL',
}),
};
// eslint-disable-next-line @typescript-eslint/no-explicit-any
public static get flags(): Interfaces.FlagInput<any> {
// …
```
=> feat: make global flags settable

src/help/index.ts
Move all instances of `console.log` to a single class method in `Help`. Doing so allows custom help classes to modify how help is logged to the console.
=> feat: move console.log to single class method

src/module-loader.ts
Support ESM module resolution for typescript directories
Fixes #421
=> feat: support TS directory imports for ESM

src/parser/flags.ts, test/parser/parse.test.ts
Currently, custom flags do not honor the `multiple` option. This fixes the issue by only overriding the `multiple` default if explicitly provided in `options`.
=> fix bug where custom flags do not respect multiple option

MIGRATION.md
Fix a mis-spelling (and broken link), and clarify the last paragraph.
=> MIGRATION.md: fix a minor typo and lack of clarity

src/command.ts
Adds `stderr` method to `Command` for logging to stderr
Fixes #392
=> feat: add stderr method

src/command.ts, src/interfaces/parser.ts
Removes the need to instantiate `flags` in order for `globalFlags` to be recognized
```typescript
import {Command, Flags} from '@oclif/core'
export abstract class BaseCommand extends Command {
static _globalFlags = {
config: Flags.string({
description: 'Specify config file',
}),
};
static flags = {}; // NOTE: Required otherwise _globalFlags is ignored.
}
```
```typescript
import {Command, Flags} from '@oclif/core'
export abstract class BaseCommand extends Command {
static _globalFlags = {
config: Flags.string({
description: 'Specify config file',
}),
};
}
```
Fixes #444
=> feat: improve the instantiation of global flags

src/command.ts
Make order of `enableJsonFlag` and `flags` declaration irrelevant
Fixes #449
=> fix: flag setter order

src/config/config.ts
Throw the right error when a command is run by the `command_incomplete` hook and fails
=> fix: throw appropriate error in runCommand

src/command.ts, src/interfaces/parser.ts, src/parser/index.ts, src/parser/validate.ts
- Restore flag typings lost in 1.12.0
- Support types on global flags
Fixes #452
=> fix: flag types

src/interfaces/parser.ts
Because of how `globalFlags` is typed, if you **do not** define any global flags then the `flags` returned from `Command.parse` will include `{ [flag: string]: unknown }`, which prevents typescript from erroring when you're attempting to access a non-existent flag.
This PR changes the default type for `flags` and `globalFlags` from `{ [flag: string]: unknown }` to `object`. Doing so removes the index signature and allows typescript to fail when accessing a non-existent flag. Unfortunately, this requires using the `object` type which is [discouraged](https://github.com/typescript-eslint/typescript-eslint/blob/v4.31.2/packages/eslint-plugin/docs/rules/ban-types.md).
The alternative to this wrapping the returned flags in a new generic type that removes the index signature,
```typescript
type …
```
=> fix: improve flag types

src/config/config.ts
restore old `@oclif/config` behaviour 
(see: https://github.com/oclif/config/blob/b1ff958d5f017f2321eb7d2efa98bb6e61e1c513/src/config.ts#L277) because 
`oclif readme` calls `await Config.load({root: cwd, devPlugins: false, userPlugins: false})`
(see https://github.com/oclif/oclif/blob/f80dcfcad472205e3c15078fa0f937489d1833c6/src/commands/readme.ts#L41) 
with `devPlugins: false` to skip `loadDevPlugins()` and exclude devPlugins in the created readme file.
=> fix: skip loadDevPlugins

src/cli-ux/index.ts
This fixes the flush function never resolving, `process.stdout.write('')` will return true if the writing chunk was accepted, only if it returns false we'll need to listen to the drain event.
More info on the Stream documentation -> https://nodejs.org/docs/latest-v14.x/api/stream.html#stream_writable_write_chunk_encoding_callback
=> fix: flush not hitting drain condition

src/command.ts
Reverts the change made in #460 
The fix does not work when:
1. Base `Command` class sets `enableJsonFlag = true`
2. There are multiple subclasses, one of which sets `enableJsonFlag = false`
In that scenario all subclasses will have the json flag disabled instead of just the one. 
This bug is currently affecting plugin-deploy-retrieve so I think we should revert this for now so that we can take our time coming up with a more thorough solution
=> fix: revert #460

src/cli-ux/index.ts
Sorry for not just creating PR to start. This addresses #464.
Some of commands are timing out when using the cli-ux flush implementation, this makes it easy to increase the timeouts for some folks (like me).
=> allow custom timeouts for ux flush

src/parser/flags.ts, test/parser/parse.test.ts
before: integer, directory, and file flags allowed you to pass a `parse` function, but ignored that (overwriting with its own parse function)
This change will
1. run the flags' built-in parse function, if any
2. run the passed-in parse function, if any
the `url` flag type did not previously accept a `parse` function, and therefore has no changes
=> feat: all oclif flag types support custom parsers

src/parser/parse.ts, test/parser/parse.test.ts
Hey, I found this issue that when I try to pass a flag as an environment variable it is not validated if this value is on the options field.
An example would be
```javascript
export default class MyCommand extends Command {
static flags = {
foo: Flags.string({
env: 'FOO',
options: ['valid1', 'valid2']
})
}
}
```
My understanding here is that if I execute the command with the `FOO` environment variable as `invalid` the parsing should fail and an error message should be displayed, this is not happening.
I added a couple of tests that verify this behavior and fixed it on this PR.
=> fix: parser doesn't validate against options parameter if the value is provided through an env var

src/parser/parse.ts, test/parser/parse.test.ts
fixes #487
I am happy to contribute to the docs if this is accepted.
=> fix: support environment variables for boolean flags

src/interfaces/parser.ts, src/parser/parse.ts, test/parser/parse.test.ts
=> fix: throw if unexpected argument

src/help/index.ts
We have commands with a lot aliases, lately this means help text looks like this:
```
bin/run app add --help
...
COMMANDS
app add action      Add new actions
app add actions     Add new actions
app add event       Add a new Adobe I/O Events action
app add events      Add a new Adobe I/O Events action
app add ext         Add new extensions or a standalone application to the project
app add extension   Add new extensions or a standalone application to the project
app add extensions  Add new extensions or a standalone application to the project
app add service     Subscribe to Services in the current Workspace
app add services    Subscribe to Services in the current Workspace
```
with this pr, it looks like:
```
COMMANDS
app add action      Add new actions
app add event       Add a new Adobe …
```
=> only output help for subcommands, no aliases

package.json, src/command.ts, src/interfaces/parser.ts, src/parser/index.ts, src/parser/util.ts, test/help/format-command-with-options.test.ts, test/help/format-command.test.ts, test/help/format-commands.test.ts, test/help/format-root.test.ts, test/help/format-topic.test.ts, test/help/format-topics.test.ts, test/help/help-test-utils.ts, yarn.lock
Update types to work with typescript@4.8.3
Fixes #482 
@W-11757550@
=> fix: work with 4.8.3

src/command.ts
…
fix bug when using tsyringe `@autoInjectable()` decorator the parser cannot read args from class
there 2 fixes for the issue, the first in the this PR and the second to pass args manually
```
const { args, flags } = await this.parse({...Connect, args: Connect.args });
```
maybe the fix is related to  #603
=> the spread operator doesn't work with getters so we have to manually add it here (same for args)

src/config/config.ts, src/interfaces/parser.ts, src/parser/parse.ts, test/integration/plugins.e2e.ts, test/integration/util.ts, test/parser/parse.test.ts
Support flag aliases
```typescript
static flags = {
name: Flags.string({
char: 'n',
summary: 'Name to print.',
required: true,
aliases: ['username', 'user-name'],
}),
}
```
[skip-validate-pr]
=> feat: support flag aliases

src/command.ts, test/command/command.test.ts
Fixes #525 
Only show flag deprecation warning if the deprecated flag was provided by the user.
=> feat: make flag deprecation warnings less noisy

src/parser/parse.ts, test/parser/parse.test.ts
When an `env` is set for a boolean flag, if the user doesn't actually specify the value in their ENV, it ends up being treated as though they'd specified `false`. I don't think this is the correct behavior; instead, it should be considered unspecified.
This is especially relevant in 2 cases:
1. Boolean flags with `default: true`. As soon as you add an `env` config, they now effectively default to false.
2. Boolean flags with mutual exclusivity. If you specify one, oclif thinks you've specified both, and the command fails. You can reproduce easily:
```ts
import {Command, Flags} from '@oclif/core'
export default class Repro extends Command {
static description = 'Reproduce exclusive flags bug'
static flags = {
exclusive1: Flags.string({
required: false,
env: 'SOME_ENV_VAR_1',
exclusive: …
```
=> fix: ignore unset environment variables

src/cli-ux/action/base.ts, src/cli-ux/prompt.ts
It's been a long standing issue that prompt returns a `Promise<any>` when it clearly should return `Promise<string>`. It's because the wrapper methods `pauseAsync()` don't forward their types along from the wrapped functions.
```ts
// This should not be valid
const foo: number = await = CliUx.ux.prompt('')
// this should be the normal type
const foo: string = await = CliUx.ux.prompt('')
```
I tried to sign the CLA but it failed the first time, and every subsequent time now I get `You already signed the CLA on 2022-10-25`.
=> Fix OclifUX.ux.prompt() return type

src/cli-ux/styled/table.ts
Hi! 
I've noticed that table is using `stdtermwidth` from `@oclif/screen` which is not good as screen implementation from core. 
Using screen from `@oclif/core` is now possible to use `process.env.OCLIF_COLUMNS=80` for example in tests or other places.
=> Table: use screen from @oclif/core

src/interfaces/parser.ts, src/parser/parse.ts, test/parser/parse.test.ts
=> feat: handle custom parser nested array for multiple flag

src/parser/validate.ts, test/parser/validate.test.ts
We have certain scenarios where we want to disallow users from using a `--no` flag when another flag is present. It seems we can do this by checking the value of the flag we want to disallow in `when`, but it ignores `false` values. 
```
action: Flags.string({ 
description: "Deploy a specific action", 
exclusive: [{ name: 'actions', when: async (flags) => flags.actions === false }] 
}),
actions Flags.boolean({ 
description: "Deploy actions", 
allowNo: true 
})
```
```
bin/run app deploy --action=a --no-actions
<success>
```
With this PR, the above will throw an error.
```
The following error occurred:
--actions=false cannot also be provided when using --action
See more help with --help
```
Closes https://github.com/oclif/core/issues/556
Currently a draft PR, because this was added without …
=> allow flags to have false value in when

src/config/config.ts
Add compatibility for [v2](https://github.com/oclif/core/pull/539) args so that CLIs built on v1 can run plugins built on v2
=> feat: add forwards compatibility for v2 args

src/main.ts, test/command/main.test.ts
This change allows callers to interact with the result of commands directly rather than having to rely on the filesystem as an intermediary.
=> Fixes #592 by directly returning the result of commands to the caller

src/config/config.ts, src/config/plugin.ts, src/interfaces/hooks.ts, src/interfaces/pjson.ts, src/interfaces/plugin.ts
Adds support for just-in-time plugin installation
Related:
https://github.com/oclif/oclif/pull/1009
https://github.com/salesforcecli/plugin-trust/pull/343
To use JIT plugins, add the following to the oclif section of the package.json
```json
"oclif": {
"jitPlugins": {
"@oclif/plugin-version": "^1.1.3", // this can be any valid semver
}
}
```
1. Checkout all branches and run `yarn && yarn build`
- https://github.com/oclif/core/pull/533
- https://github.com/oclif/oclif/pull/1009
- https://github.com/salesforcecli/plugin-trust/pull/343
2. yarn link `@oclif/core` to `oclif` branch (https://github.com/oclif/oclif/pull/1009)
3. yarn link `@oclif/core` to `@salesforce/plugin-trust` branch (https://github.com/salesforcecli/plugin-trust/pull/343) 
4. yarn link `@oclif/core`, `oclif`, …
=> feat: support JIT plugin installation

src/parser/errors.ts, src/parser/parse.ts, test/parser/parse.test.ts
* feat: specify flag name in parse errors
* fix: impl. for specifying flag name in parse errors
=> feat: specify flag name in parse error message (#589)

src/help/index.ts
Ignored `hasDynamicHelp` when generating help for JIT plugins
=> fix: ignore hasDynamicHelp if JIT plugin

src/parser/parse.ts, test/parser/parse.test.ts
1. --multiFlag would validate options agains the combined input BEFORE splitting when it used a delimiter.
2. strings can be double-quoted when they contain spaces.  This removes surrounding quotes from the items before validating against the options.
side note about error messages assertion changes:
test cases would run find from `yarn test` but fail when running the individual test becuase of ASCII color codes in the results.  They've been modified to "include" the expected strings to make them color-blind
=> fix: handling quoted strings and options validation for comma-delimited multiple-flag

src/config/config.ts
Adds new `captureErrors` parameter to `Config.runHook`. If it's `true`, errors from hooks will be captured and returned to the caller; if it's `false` or `undefined`, all errors will be thrown
Fixes #515 
Fixes https://github.com/oclif/oclif/issues/1083
@W-12514447@
=> feat: add param to runHook to capture errors

src/parser/validate.ts, test/parser/validate.test.ts
I'm updating our CLI to v2 and we have noticed that this new check in `Parser.validate` doesn't respect `strict` to false.
Fixes #616
=> Avoid nonExistentFlag error with strict set to false

src/config/util.ts, src/help/util.ts, test/config/util.test.ts, yarn.lock
Simple change to improve command lookup perf
=> fix: change useable ids to set to improve search perf

src/performance.ts
Stop any unstopped performance markers when collecting performance results
=> fix: stop any unstopped markers when collecting perf results

package.json, src/config/plugin.ts, src/config/ts-node.ts
Register ts-node for linked plugins so that developers don't have to compile their plugin before running it
More context: https://github.com/forcedotcom/cli/issues/1664
@W-12652231@
- `yarn link @oclif/core` in sfdx-cli
- cd to `oclif/plugin-plugins`
- run `sfdx plugins link`
- run `rm -rf lib/`
- cd to sfdx-cli
- cd to `oclif/plugin-plugins`
- run `yarn build`
- cd to sfdx-cli
=> Auto-compile linked plugins

src/config/config.ts, src/interfaces/config.ts
Adds `Config.versionDetails` so that multiple consumers can get detailed version information without having to use plugin-version directly
=> feat: add Config.versionDetails

src/interfaces/config.ts, src/interfaces/index.ts
=> fix: add version details property to config interface

src/module-loader.ts
This fixes a bug where linked plugins with hooks were causing a CLI to fail with the `ModuleLoadError: [MODULE_NOT_FOUND] require failed to load`.
https://github.com/oclif/core/pull/650 introduced compilation at runtime for linked TS plugins using `ts-node`.
When trying to compile hooks from linked plugins oclif isn't passing the `plugin.type` prop to the ts path resolver so `tsPath` was just skipping the compilation step.
**Repro**
- cd to `plugin-info` (doctor hook)
- run `rm -rf lib`
- run `../sfdx-cli/bin/run plugins:link .`
- run `../sfdx-cli/bin/run`, should see the `MODULE_NOT_FOUND`
**QA**
- yarn link @oclif/core in sfdx-cli
- cd to `plugin-info` (doctor hook)
- run `rm -rf lib`
- run `../sfdx-cli/bin/run plugins:link .`
- run `../sfdx-cli/bin/run`, CLI should work.
=> fix: pass plugin type when resolving a module path

src/command.ts, src/help/util.ts, test/command/command.test.ts
To improve the command flag deprecation warnings, the flag name and (if it exists) the flag short char is included in the warning.
@W-12528771@
=> fix: add flag name and short char to deprecation message

src/config/config.ts, src/config/plugin.ts, src/help/index.ts, src/interfaces/parser.ts, src/interfaces/plugin.ts, src/parser/parse.ts, src/parser/validate.ts, test/command/command.test.ts, test/help/help-test-utils.ts, test/parser/parse.test.ts
=> feat: add param noSensitiveData to Plugin.load

src/config/config.ts, src/config/plugin.ts, src/help/index.ts, src/interfaces/parser.ts, src/interfaces/plugin.ts, src/parser/parse.ts, src/parser/validate.ts, test/command/command.test.ts, test/help/help-test-utils.ts, test/parser/parse.test.ts
This reverts commit b4a738e40735c40dbf633546011c4a860ebff46c.
Causing unexpected exception when running defaultHelp functions that throw errors.
=> Revert "feat: add param noSensitiveData to Plugin.load (#665)"

.github/workflows/test.yml, test/integration/plugins.e2e.ts
@W-13130355@
change e2e test to account for https://github.com/oclif/plugin-plugins/pull/609
oclif can use the salesforcecli/gh-workflows UT actions and lockfile check (no secrets:inherit)
node20 problem was this (newer supports node20) https://github.com/salesforcecli/cli/pull/873/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L241
=> test: restore node20 e2e

src/config/config.ts
This PR fixes an issue where CLIs that includes `@oclif/plugin-legacy` and at least one [old, invalid plugin ](https://github.com/oclif/core/blob/main/src/config/plugin.ts#L161-L165) would get legacy plugins as the only ones installed.
left: ci-v5 plugin installed, shows as the only plugin (`--core` should show core plugins too), `plugins:inspect webhooks` fails even though `@heroku-cli/plugin-webhooks` is a core plugin. 
right: with oclif fix, `plugins:inspect` is able to find it.
plugin-legacy init hook where invalid, legacy plugins are converted:
https://github.com/oclif/plugin-legacy/blob/main/src/hooks/init.ts
1. install Heroku CLI: `npm i -g heroku`
2. check core plugins: `heroku plugins --core`, this only returns `addons-v5 8.1.7 (core)` because it's the first invalid plugin found. …
=> fix: correctly load legacy plugins

src/parser/parse.ts, test/parser/parse.test.ts
@W-13157931@
improves flag validation to prevent a flag being read as a flag value
note: I was unable to get this linked and building through my cli. I took a TDD approach instead and wrote the UTs first, and then fixed them
=> fix: improve flag validation

perf.txt, src/parser/parse.ts, test/parser/parse.test.ts
fix https://github.com/oclif/core/issues/729
[boolean flags have a built-in `parse` function even if the user doesn't specify it.  It was easier to filter out `undefined` flags after calculating all the valus than to try to interfere with boolean flags before the `default` logic happens]
=> fix: flags omit undefined for boolean flags

src/parser/parse.ts, test/parser/parse.test.ts
Allow an empty string as a flag default. Used in a few places and caused NUTs to fail
https://github.com/salesforcecli/plugin-community/blob/main/src/commands/community/create.ts#L60
https://github.com/salesforcecli/plugin-custom-metadata/blob/main/src/commands/cmdt/generate/object.ts#L64
[@W-13754930@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-13754930)
=> Allow empty flag default

src/help/index.ts
@W-13753346@
https://github.com/forcedotcom/cli/issues/2301
=> fix: correctly print help when only command found and passed with help

src/command.ts
=> fix: corrected return type for Command.exit (#715)

src/module-loader.ts
After I changed my setup according to https://oclif.io/docs/esm, I got an error when loading `.tsx` files/commands.
`(node:3021523) [ERR_REQUIRE_ESM] Error Plugin: test-cli: Must use import to load ES Module: /[...]/test-cli/src/commands/hello/index.tsx`.
This PR adds the `.tsx`, `.jsx` and `.mts` extension to be handled in `ModuleLoader::isPathModule`.
=> feat: add extensions to esm checking

.github/workflows/test.yml, src/interfaces/parser.ts, src/parser/parse.ts, src/util.ts, test/util.test.ts
- Reverts use of `Array.at` to ensure Node 14 compatibility
- Fixes #731 
- Fixes https://github.com/oclif/plugin-plugins/issues/624)
- Adds back support for reading flag values from stdin in Node 14 (See JSDoc on `readStdinLegacy` to understand the drawbacks of keeping this in)
- Fixes #630
- Fixes https://github.com/oclif/oclif/issues/1106
- Fixes regression with `Flags.help` and `Flags.version`
- Fixes #740
=> fix: support node 14 again

src/command.ts, src/config/config.ts, src/interfaces/config.ts, test/config/config.test.ts
=> feat: deprecate scopedEnvVarKey for scopedEnvVarKeys which accounts for binAliases

src/flags.ts
without this change `my-cli command --help` always uses the default help class.
=> fix: use configured help class in --help

src/command.ts, src/config/config.ts, src/interfaces/plugin.ts
Proof of concept for fixing `Config` mismatch issue described [here](https://github.com/forcedotcom/cli/issues/2426#issuecomment-1693415044)
```
$ sf update -v 2.5.7
$ cd plugin-plugins
$ sf plugins link
$ sf plugins --core
TypeError: this.config.getPluginsList is not a function
$ yarn link @oclif/ocre
$ sf plugins --core
@oclif/plugin-autocomplete 2.3.6 (core)
@oclif/plugin-commands 2.2.22 (core)
@oclif/plugin-help 5.2.17 (core)
@oclif/plugin-not-found 2.3.37 (core)
@oclif/plugin-plugins 3.3.0 (link) /Users/mdonnalley/repos/oclif/plugin-plugins
@oclif/plugin-search 0.0.22 (core)
@oclif/plugin-update 3.1.32 (core)
@oclif/plugin-version 1.3.8 (core)
@oclif/plugin-warn-if-update-available 2.0.48 (core)
@oclif/plugin-which 2.2.30 (core)
@salesforce/cli 2.5.7 (core)
apex 2.3.10 (core)
auth …
```
=> feat: reload Config before running command

src/config/config.ts
Adds forwards compatibility for when v3 makes `Config.plugins` a `Map`
=> feat: forwards compatibility for config reload

src/config/ts-node.ts, test/integration/esm-cjs.ts
Skip ts-node registration for all ESM plugins, regardless of the root plugin type. The node ecosystem is not mature enough to support auto-transpiling ESM modules at this time.
See the following:
- https://github.com/TypeStrong/ts-node/issues/1791#issuecomment-1149754228
- https://github.com/nodejs/node/issues/49432
- https://github.com/nodejs/node/pull/49407
- https://github.com/nodejs/node/issues/34049
=> feat: skip ts-node register for ESM plugins

test/parser/parse.test.ts
=> test: ut for charAliases

package.json, src/config/ts-node.ts, test/integration/sf.e2e.ts
Move `ts-node` to devDependency. This will require linked plugins to have `ts-node` as a devDependency
Fixes #735
=> feat: remove ts-node

src/help/index.ts, test/help/fixtures/fixtures.ts, test/help/show-help.test.ts
Show standard deprecation warning in help when using a deprecated alias
@W-14208399@
Fixes https://github.com/oclif/core/issues/800
=> fix: show deprecation warning in help when using deprecated alias

src/config/config.ts
=> fix: prevent postrun hook from running on uninstalled plugins

src/command.ts, src/execute.ts, src/help/command.ts, src/help/formatter.ts, src/help/index.ts, test/help/fixtures/fixtures.ts, test/help/format-command-with-options.test.ts, test/help/format-command.test.ts, test/help/format-commands.test.ts, test/help/help-test-utils.ts, test/help/show-customized-help.test.ts
- Update `execute` examples
- Only use `Command.Loadable` in `Help` code
- Un-fancy-ify `formatCommand` tests
=> fix: only Command.Loadable in Help

.github/workflows/test.yml, src/flags.ts, src/interfaces/parser.ts, src/interfaces/pjson.ts, test/integration/sf.e2e.ts, test/interfaces/flags.test-types.ts
Fixes issue with custom flags with union type unnecessarily enforcing `multiple: true`
Fixes #812 
@W-14261473@
=> fix: custom flags with union type

package.json, src/config/plugin.ts, src/util/fs.ts, test/parser/parse.test.ts, test/util/fs.test.ts
No longer use `fs.access` to check for file existence, which is not recommended,
>Using fsPromises.access() to check for the accessibility of a file before calling fsPromises.open() is not recommended. Doing so introduces a race condition, since other processes may change the file's state between the two calls. Instead, user code should open/read/write the file directly and handle the error raised if the file is not accessible. 
Source: https://nodejs.org/api/fs.html#fspromisesaccesspath-mode
Fixes #815
@W-14266572@
=> fix: avoid fs.access for checking for file existence

.eslintrc.json, README.md, src/config/ts-node.ts, src/execute.ts, test/integration/plugins.e2e.ts
- Warn when `ts-node` is being used to execute `bin/dev.js` and node is >= 20
- Fall back to compiled source when `ts-node` cannot be used
Fixes https://github.com/oclif/core/issues/817
@W-14270164@
=> fix: warn about ts-node and node 20

src/util/cache-command.ts
Plugins that use v2 but are linked in a CLI using v3 are missing flags since v3 no longer uses `_flags` under the hood of `Command`
=> fix: use _flags for linked v2 plugins

src/interfaces/pjson.ts
So we can remove this `any`: https://github.com/oclif/plugin-warn-if-update-available/blob/main/src/hooks/init/check-update.ts#L16
=> fix: add types for warn-if-update-available

src/config/config.ts, src/config/plugin-loader.ts, src/config/ts-node.ts, src/interfaces/plugin.ts, test/config/config.flexible.test.ts, test/config/config.test.ts
- Never allow `MODULE_NOT_FOUND` error from hook to exit the process
- Allow user plugins from github urls to be auto-transpiled in production (CJS only)
QA
(from `salesforcecli/cli` repo)
- yarn link `@oclif/core`
- `bin/run.js plugins install https://github.com/oclif/plugin-test-esm-1.git`
- `bin/run.js plugins`
- `bin/run.js plugins install https://github.com/oclif/plugin-test-cjs-1.git`
- `bin/run.js plugins`
You should see no errors.
You should also see the hook text being output by the init hook from `@oclif/plugin-test-cjs-1`
You should **not** see the hook text being output by the init hook from `@oclif/plugin-test-esm-1` since we can't auto-transpile ESM plugins in production. This will be fixed by this [commit](https://github.com/oclif/plugin-plugins/pull/683/commits/88e9d021ad34 …
=> fix: handle ModuleLoadError from hooks

package.json, src/config/plugin.ts, src/config/ts-node.ts, src/config/util.ts, src/util/find-root.ts, yarn.lock
- Add ability to find plugin root for PnP plugins that lack a `main` or `export` defined in their package.json.
- Put all `findRoot` related functionality into its own file for cleanliness purposes
Huge thanks to @danieltroger for figuring out the implementation for this!
Fixes #806 
@W-14331357@
=> feat: better support yarn PnP

package.json, src/config/config.ts
Clear out all commands (and aliases) belonging to legacy plugins before reloading them. Doing this ensure that the `determinePriority` won't keep the initial command that was loaded.
@W-14306614@
=> fix: clear commands belonging to legacy plugins before reloading

src/config/config.ts, src/config/plugin.ts
Run `tsPath` on all hook file paths to ensure that the correct path is used at run time in development
=> feat: run tsPath on hooks

src/config/ts-node.ts, src/util/fs.ts, test/config/ts-node.test.ts
Always use `tsconfck` again for parse tsconfig.json
Fixes #849
=> fix: support jsonc tsconfig

CHANGELOG.md, package.json, src/config/plugin.ts
Removes a warning about an empty `files` attribute in the `package.json` file.
The warning is unnecessary, as it is valid not to have `files`, and use `.npmignore` instead to
specify what files should not be included in the package, and then include everything else by
default.
Closes #851
=> fix: removes empty files attribute warning

CHANGELOG.md, package.json, src/config/config.ts, src/config/plugin.ts, src/util/find-root.ts
- Improves plugin loading perf by
- defer running `tsPath` on hook paths until the hook needs to be executed
- only load `commandsDir` if it's needed by `findCommand` or `getCommandIDs`
- use the manifest to populate `this.commandIDs` if possible
- Remove unnecessary `files` check (Closes #851)
- Improve `find-root` debug logging
=> fix: improve plugin loading performance

src/config/ts-node.ts, src/performance.ts, test/perf/parser.perf.ts
- Moves up the `isProduction` check in `tsPath` so that the debug logs are more accurate about why ts-node registration is being skipped
- Adds `Process Uptime` perf debug log
- Renames `Total Time` debug log to `Oclif Time`
- Adds debug log to explain why `Config Load Time` could be greater than `Oclif Time`
=> fix: move up prod check in tsPath

src/help/command.ts, test/help/format-command-with-options.test.ts, test/help/format-command.test.ts
Indent flags with no char below each other, like docker cli does
----
when combined with the theme feature this is the end result
=> feat: improve flags indentation

src/help/command.ts, test/help/format-command-with-options.test.ts, test/help/format-command.test.ts
=> feat: indent all flags with no char below each other (#863)

src/cli-ux/README.md
This document is missing '. bind (this)'`, This can lead to the following errors:
```
TypeError: this.jsonEnabled is not a function
at Object.log [as printLine] (/Users/user/xx-cli/node_modules/@oclif/core/lib/command.js:224:19)
at Table.outputTable (/Users/user/xx-cli/node_modules/@oclif/core/lib/cli-ux/styled/table.js:244:21)
at Table.display (/Users/user/xx-cli/node_modules/@oclif/core/lib/cli-ux/styled/table.js:137:22)
at Object.table (/Users/user/xx-cli/node_modules/@oclif/core/lib/cli-ux/styled/table.js:301:39)
at List.run (/Users/user/xx-cli/src/commands/list/index.ts:56:19)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async List._run (/Users/user/xx-cli/node_modules/@oclif/core/lib/command.js:304:22)
```
The official website is normal with the addition …
=> Fix this.log.bind(this)

src/help/util.ts, test/help/util.test.ts
(this is a duplicate of #886 which had the wrong branch and was closed)
This PR fixes an edge case bug in command ID parsing when the topic separator is a space
When `argv` contains an empty string arg, the command ID extracted contains an extra colon.
An empty string arg can occur when running the CLI as part of a script.
Example:
```bash
set FOO=""
cli cmd ${FOO} --bar
```
Result: command not found "cmd"
Root cause: incorrect parsing in `standardizeIDFromArgv`, which for the above example returned `cmd:` as the command ID.
=>  fix: command not found on empty arg

src/help/util.ts, test/help/util.test.ts
Merges #887 
when `topicSeparator` is a space and an empty string arg is given, the searched command ID had an extra colon:
example:
```bash
set FOO=""
cli cmd ${FOO} --bar
```
result: command not found "cmd"
root cause: incorrect parsing in `standardizeIDFromArgv`, which for the above example returned `cmd:` as the command ID.
=> fix: command not found on empty arg (#887)

src/interfaces/parser.ts, src/parser/parse.ts, test/parser/parse.test.ts
This is a port of https://github.com/oclif/parser/pull/79 by @cxam
Original description:
This feature aims to address the issue outlined in https://github.com/oclif/oclif/issues/190 to only allow a single value to be assigned for each flag that has the `multiple` option set. It's a non-breaking change that requires you to include the `singleValue` boolean in your flag options.
In the command `cmd -a foo bar`, it's generally accepted that `bar` becomes a positional argument and should be the default behaviour. Unfortunately, the [PR](https://github.com/oclif/parser/pull/25) that broke default behaviour has been part of this project for a while now and I feel providing the user an option to change this back would be the best course of action unless a breaking release is planned for oclif. …
=> feat: add 'multipleNonGreedy' flag option to assign only one value per multiple flag

src/parser/errors.ts, src/parser/parse.ts
Preserve the original error thrown from a flag's `parse` since downstream consumers might be expecting a certain instance of `Error`
=> fix: preserve original error coming from failed flag parsing

src/interfaces/parser.ts, src/parser/parse.ts, test/parser/parse.test.ts
Adds `only` option to `allowStdin` flag property. Setting it to`only` will throw if the user does not provide `-` as the value
=> feat: add 'only' option to allowStdin

src/config/config.ts, src/help/command.ts, src/interfaces/pjson.ts
Allow the location of the `theme.json` to be configured by the root CLI's package.json. This allows CLIs to ship a theme to their users
```json
"files": ["theme.json"],
"oclif": {
"theme": "./theme.json"
}
```
If users have their own theme at `~/.confg/<CLI>/theme.json` then it will be merged in with the default theme, with the user theme taking precedence. 
@W-14527856@
=> feat: allow theme file to be configurable

src/parser/parse.ts, test/parser/parse.test.ts
Currently, flags and args read from stdin are lost whenever `Parser.parse` is called multiple times. This PR caches the value read from stdin so that `Parser.parse` can be called multiple times.
This PR also:
- decreases timeout for reading stdin (from 100ms to 10ms)
- Flags with `allowStdin: 'only'` are no longer required to have `-` provided as the value (it's assumed)
@W-14954770@
https://github.com/forcedotcom/cli/issues/2690
=> fix: cache stdin

src/cli-ux/prompt.ts, test/cli-ux/prompt.test.ts
Use `readline.createInterface` for `ux.prompt`
Fixes #952 
@W-15023621@
=> fix: allow long text in ux.prompt

src/cli-ux/prompt.ts, test/cli-ux/prompt.test.ts
Only set a timeout for a prompt if `process.stdin.TTY` is truthy
**QA**
1. checkout this branch and `yarn build`
2. `yarn && yarn build` in plugin-not-found directory
3. `yarn link @oclif/core` in plugin-not-found directory
4. `sf plugins link --no-install` in plugin-not-found directory
5. Test the following: 
Standard misspelled command scenario. Prompt should timeout after 10 seconds.
```
❯ time sf verson
›   Warning: @oclif/plugin-not-found is a linked ESM module and cannot be auto-transpiled. Existing compiled source will be used
›   instead.
›   Warning: verson is not a sf command.
Did you mean version? [y/n]:
›   Error: Run sf help for a list of available commands.
sf verson  0.55s user 0.09s system 6% cpu 10.429 total
```
Piping answer to prompt. Should not wait for timeout.
```
❯ …
```
=> fix: only set timeout for TTY

src/main.ts
Use `Help` class directly instead of assuming that plugin-help is installed.
**QA**
- pull branch, `yarn && yarn build`
- `oclif generate my-cli`
- Remove all references to plugin-help from my-cli's package.json
- Remove `src/hello/index.ts`
- `yarn link @oclif/core` in my-cli directly
- Run `bin/dev.js hello` - you should see help output for the `hello` topic
Fixes #848 
@W-15103728@
=> fix: dont assume plugin-help is installed

src/cli-ux/styled/table.ts, test/cli-ux/styled/table.test.ts
modify replace with replaceAll as mentioned in this issue : https://github.com/oclif/core/issues/944#issue-2126189996
=> Fix: correctly escapes double quotes when converting ux.table to csv

src/cli-ux/styled/table.ts, test/cli-ux/styled/table.test.ts
Merges #977 
* Fix: correctly escapes double quotes when converting ux.table to csv
modify replace with replaceAll as mentioned in this issue : https://github.com/oclif/core/issues/944#issue-2126189996
* test: complete ux.table test to check if double quotes escaping is correct
=> fix: correctly escapes double quotes when converting ux.table to csv (#977)

src/parser/parse.ts, src/parser/validate.ts, test/parser/validate.test.ts
Allow args to be an empty string, e.g. `my-cli hello ''`
Fixes #982 
@W-15161625@
=> fix: allow arg to be empty string

src/config/plugin.ts, src/module-loader.ts
Improve error handling for module load errors by:
- always printing `error.message`
- better naming conventions
**Testing**
- `oclif generate my-cli` (select ESM)
- `ERR_UNKNOWN_FILE_EXTENSION` error: 
- `NODE_ENV=development bin/run.js hello world --from oclif`
- `ERR_MODULE_NOT_FOUND` error: 
- add invalid import to compiled code (e.g. `import foo from 'bar'` in `./dist/commands/hello/world.js`)
- `bin/run.js hello world --from oclif`
Fixes #986 
@W-15161976@
=> fix: improve module load error handling

package.json, src/config/config.ts, src/config/plugin-loader.ts, src/interfaces/plugin.ts, test/config/fixtures/wildcard/package.json, test/config/fixtures/wildcard/src/commands/foo.ts, test/config/fixtures/wildcard/tsconfig.json, test/config/wildcard-plugins.test.ts
Allow plugins to be defined with [minimatch](https://www.npmjs.com/package/minimatch) patterns. For instance: 
```json
{
"dependencies": {
"@oclif/core": "^3",
"@oclif/plugin-help": "^6",
"@oclif/plugin-plugins": "^4",
"@org/cool-plugin": "^1",
"@org/awesome-plugin": "^1",
},
"oclif": {
"plugins": [
"@oclif/plugin-*",
"@org/*",
]
}
}
```
This PR also exposes a new option on `Config` called `pluginAdditions` that informs `Config` of additional plugins that should be loaded. This is solves the use case described in https://github.com/oclif/core/pull/976
`pluginAdditions` is defined as:
```
pluginAdditions?: {
core?: string[] // core plugins that should be loaded
dev?: string[] // dev plugins that should be loaded
path?: string // path to load these plugins from (defaults to root plugin's …
```
=> feat: support plugins with wildcards

src/cli-ux/action/base.ts, src/cli-ux/config.ts, src/cli-ux/index.ts, src/cli-ux/prompt.ts, src/cli-ux/styled/table.ts, src/cli-ux/write.ts, src/index.ts
Mark `ux` module as deprecated. See https://github.com/oclif/core/discussions/999 for context.
=> feat: deprecate ux module

.git2gus/config.json, src/help/command.ts
=> fix: remove configured id from usage override

src/help/command.ts, src/help/docopts.ts, test/help/format-command.test.ts, test/help/help-test-utils.ts
Print `...` on arg if `static = false`
```
❯ bin/dev.js hello world --help
Say hello world
USAGE
$ oex hello world [THINGS...]
ARGUMENTS
THINGS...  things to say
DESCRIPTION
Say hello world
EXAMPLES
$ oex hello world
hello world! (./src/commands/hello/world.ts)
```
Fixes https://github.com/oclif/plugin-help/issues/58
Fixes https://github.com/oclif/oclif/issues/234
Fixes https://github.com/oclif/plugin-help/issues/56
=> feat: print ellipsis on arg if static is false

src/config/plugin.ts, src/config/ts-path.ts
Errors emitted from ts-node are objects with [custom inspections](https://nodejs.org/api/util.html#custom-inspection-functions-on-objects) instead of errors or strings, which causes this error when emitting the warning:
```
TypeError: The "warning" argument must be of type string or an instance of Error. Received src/commands/task/get.tsx(2,9): error TS6133: 'Box' is declared but its value is never read.
at process.emitWarning (node:internal/process/warning:176:11)
at Plugin.warn (/Users/mdonnalley/repos/oclif/core/lib/config/plugin.js:372:17)
at /Users/mdonnalley/repos/oclif/core/lib/config/plugin.js:276:30
at async Promise.all (index 19)
at async Plugin._manifest (/Users/mdonnalley/repos/oclif/core/lib/config/plugin.js:257:24)
at async Plugin.load …
```
=> fix: ensure string is passed to process.emitWarning

src/parser/parse.ts, test/parser/parse.test.ts
- do not throw an error if a flag with allowStdin='only' is immediately followed by another flag
- include a new test
closes https://github.com/forcedotcom/cli/issues/2811
=> fix: allowStdin with no input

src/parser/parse.ts, test/parser/parse.test.ts
Merges #1046 
Fixes https://github.com/forcedotcom/cli/issues/2811
=> fix: do not throw an error if a flag with allowStdin='only' is immediately followed by another flag (#1046)

package.json, src/config/plugin.ts, src/util/find-root.ts, src/util/fs.ts, src/util/read-pjson.ts
Use [cosmiconfig](https://www.npmjs.com/package/cosmiconfig) to support rc files, which will allow consumers to use an rc file to configure oclif instead of using the package.json.
Important to note that oclif will still be dependent on the package.json to get the `name`, `version`, and `dependencies`
The following files are supported:
```
.oclifrc
.oclifrc.json
.oclifrc.yaml
.oclifrc.yml
.oclifrc.js
.oclifrc.ts
.oclifrc.mjs
.oclifrc.cjs
oclif.config.js
oclif.config.ts
oclif.config.mjs
oclif.config.cjs
```
@W-15470586@
=> feat: support rc files

src/interfaces/pjson.ts
this PR adds a type in order for [the other PR](https://github.com/oclif/plugin-update/pull/807) on oclif/plugin-update to work
=> fix: new "dont check npm" option for plugin-update 

src/command.ts, src/interfaces/flags.ts, src/interfaces/hooks.ts, src/interfaces/parser.ts, src/parser/index.ts, src/util/aggregate-flags.ts, src/util/cache-command.ts
Restore support for `baseFlags`
=> fix: restore baseFlags support

src/help/command.ts, test/help/format-command.test.ts
Only replace command id in usage if it's at the beginning of the string. This solves problem where the command id is present elsewhere in the string (e.g. if it's a single letter command id)
Note: external unit tests failing because oclif plugins are now using v4
Fixes #1089
@W-15903264@
=> fix: only replace command id in usage if it's at beginning of string

src/help/command.ts, src/help/docopts.ts, src/interfaces/parser.ts, test/help/docopts.test.ts, test/help/format-command.test.ts
Feature add for #1088 
- Made changes to the docopts formatter
- Wrote a test for the docopts changes
There is the option to include multiple example flags such that the usage string can format to something like 
`mycli -i <input-json>... <input-xml>...`
=> feat: added option to specify example flag value in docopts

src/command.ts
Fix regression in v4 where `this.parse` returned `any` for `args`
=> fix: parsed args regression

package.json
Adds export for parser
```typescript
const { parse } = await import('@oclif/core/parser');
```
Closes https://github.com/oclif/core/discussions/1097
=> fix: add export for parser

src/interfaces/index.ts, src/parser/index.ts
Exports the following under `Interfaces` and `@oclif/core/parser`
`ArgInput`
`FlagInput`
`Input`
`OutputArgs`
`OutputFlags`
`ParserOutput`
=> fix: export parser related types

package.json, src/util/read-pjson.ts, yarn.lock
Use lilconfig instead of cosmicconfig for reading rc files so that typescript doesn't get shipped
- link this branch to sf repo
- move `oclif` config from package.json to rc file (see below) (package.json should **not** contain an oclif section)
- run `bin/run.js` version (if the command succeeds you can assume that the config worked)
- note: only have a single rc file at a time, otherwise lilconfig will only use the first one it finds
**.oclifrc**
```json
{
"bin": "sf",
// etc...
}
```
**.oclifrc.json**
```json
{
"bin": "sf",
// etc...
}
```
**.oclifrc.js**
```js
export default {
bin: 'sf',
// etc...
}
```
**.oclifrc.mjs**
```js
export default {
bin: 'sf',
// etc...
}
```
**.oclifrc.cjs**
```js
module.exports = {
bin: 'sf',
// etc...
}
```
**oclif.config.js**
```js
export default {
bin: …
```
=> fix: use lilconfig

src/help/index.ts
replicate the --help behavior when a command fails, hide the symbol
fix #1111
=> fix: hide single command cli symbol on help output

src/config/plugin-loader.ts, src/util/fs.ts
Ignore the `ProdOnlyCache` when reading the user pjson because it could have been modified by a JIT install
Fixes issue with first execution of a JIT plugin failing with this error:
```
sf dev generate library                               
@salesforce/cli: Installing plugin dev@2.3.2... installed v2.3.2
›   ModuleLoadError: [MODULE_NOT_FOUND] import() failed to load /Users/peter.hale/.npm-global/lib/node_modules/@salesforce/cli/lib/commands/dev/generate/library.js: Cannot find module 
›   '/Users/peter.hale/.npm-global/lib/node_modules/@salesforce/cli/lib/commands/dev/generate/library.js' imported from /Users/peter.hale/.npm-global/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/module-loader.js
›   Code: MODULE_NOT_FOUND
```
**Testing**
1. Checkout branch, `yarn build`
2. …
=> fix: ignore cache when reading user pjson

src/config/config.ts, test/config/config.shell.test.ts
Correctly distinguish between powershell and cmd.exe
@W-11446819@
=> fix: correctly identify powershell

src/command.ts, src/errors/errors/cli.ts, src/help/command.ts, src/help/formatter.ts, src/parser/errors.ts, src/parser/help.ts
Always use `ux.colorize` to ensure consistent TTY detection
@W-16198524@
https://github.com/forcedotcom/cli/issues/2951
=> fix: use colorize to ensure proper TTY detection

src/parser/parse.ts, test/parser/parse.test.ts
Ignore escaped delimiters when splitting input string for flags with `delimiter` and `multiple`
**Before**
```
my-cli --flag one,two,three` => {flag: ['one', 'two', 'three']}
```
**After**
```
my-cli --flag one\,two,three` => {flag: ['one,two', 'three']}
```
This is useful when you have flag values that contain the delimiter but shouldn't be split.
_Depending on you shell, you might need to double escape to get the desired effect._
@W-16343745@
https://github.com/forcedotcom/cli/issues/2928
=> fix: ignore escaped delimiters

src/config/ts-path.ts
- Use file url to import tsx at runtime
- debug errors caused by importing ts-node and/or tsx
**QA**
- create new ESM cli on windows: `oclif generate my-cli --yes`
- install `tsx` globally: `npm install -g tsx`
- add `tsx` to my-cli: `npm install --save-dev tsx`
- remove ts-node from my-cli: `npm uninstall ts-node`
- update shebang in dev.js to `#!/usr/bin/env -S npx tsx --no-warnings`
- update dev.cmd to use `npx tsx` instead of `node --loader ts-node/esm --no-warnings=ExperimentalWarning`
- delete the `dist` directory
- set `DEBUG=*`
- run `bin\dev.cmd hello world`
The command should successfully run and the logs should indicate that tsx did not fail to be imported:
```
oclif:config:ts-path registering tsx at C:\Users\username\code\tsx-bug-esm +7ms
oclif:config:ts-path tsx path: …
```
=> fix: use file url to import tsx at runtime

src/ux/write.ts, test/ux/write.test.ts
Use `console.log` and `console.error` instead of `process.stdout.write` and `process.stderr.write`, to avoid losing information from back pressure on the streams
To replicate:
```js
// write.js
import {stdout} from './src/ux/write.js'
const lines = Array.from(
{length: 100},
(_, i) =>
`Line ${i} Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer convallis fringilla sollicitudin. Nunc scelerisque neque non ipsum accumsan commodo. In et porttitor eros, ut vestibulum magna. Morbi felis diam, pharetra eu dui non, sollicitudin feugiat nisi. Aliquam cursus malesuada risus, vel luctus leo ornare sed. Morbi condimentum odio id ex facilisis bibendum. Nullam consectetur consectetur viverra. Donec nec ante dui. Integer lacinia facilisis urna vitae feugiat.`,
)
for (const line of lines) …
```
=> fix: handle large throughput writes

package.json, src/index.ts
Emit process warning when oclif/core's node engine property is not satisfied
```
❯ sf version
(node:16992) Warning: Node version must be >=22.0.0 to use this CLI. Current node version: 20.13.1
(Use `node --trace-warnings ...` to show where the warning was created)
@salesforce/cli/2.60.8 darwin-arm64 node-v20.13.1
```
@W-16795546@
Fixes https://github.com/oclif/core/issues/1197
=> fix: warn about node version mismatch

src/help/index.ts
Makes the warning for deprecated aliases here: https://github.com/oclif/core/blob/cc8366a70310682a389f3ffdebd202b1860e09d8/src/help/index.ts#L202-L206
use the topic separator by passing `actualCmd.id` into `toConfiguredIds` and using *that* result for the `to` in the `Deprecation` type parameter of `formatCommandDeprecationWarning` as done here: https://github.com/oclif/core/blob/66604a36aea80be30457cf19bdfb8891d24cc4c9/src/command.ts#L311-L315
=> fix: use topic separator for deprecated alias warnings in `help`

src/command.ts, test/command/command.test.ts
Fix bug with `deprecateAliases` warning showing when flag name starts with deprecated alias.
**QA**
- `oclif generate my-cli`
- add this flag definition to `src/commands/hello/index.ts`
```
'foo-bar': Flags.boolean({
summary: 'summary',
deprecateAliases: true,
aliases: ['foo']
}),
```
- checkout this branch and run `yarn build`
- `yarn link @oclif/core` in `my-cli` directory
- `bin/dev.js hello oclif --from me --foo-bar` should **not** emit warning
- `bin/dev.js hello oclif --from me --foo` should emit warning
Fixes #1204 
@W-16866149@
=> fix: deprecated aliases bug

src/help/command.ts, src/interfaces/help.ts
Add `respectNoCacheDefault` option to help so that `oclif readme` can ignore any defaults for flags that have `noCacheDefault` property
@W-16883857@
https://github.com/forcedotcom/cli/issues/3041
=> fix: add respectNoCacheDefault to help options

src/ux/colorize-json.ts, test/ux/colorize-json.test.ts
Remove circular references when colorizing json output
https://github.com/forcedotcom/cli/issues/3051
@W-16954992@
=> fix: remove circular references when colorizing json

src/ux/colorize-json.ts, test/ux/colorize-json.test.ts
- Don't remove repeated objects from json when stringifying
- Replace circular ref with `[Circular ~]` instead of removing key altogether
Solution taken directly from [json-stringify-safe](https://www.npmjs.com/package/json-stringify-safe). We can use it directly but it hasn't been updated in over 9 years (although it's still widely used with 23 million weekly downloads)
=> fix: improve solution for handling circular json

src/config/config.ts
=> fix: fix aliases in config.commandIDs missing the default topic separator (#1229)

package.json, src/config/config.ts, yarn.lock
This reverts commit 7fd9162a165884657c2ead87f5c0e9e2fd9b708d.
We originally bumped is-wsl in attempt to resolve [this security vulnerability](https://github.com/oclif/core/issues/1210) but [apparently](https://github.com/sindresorhus/is-docker/issues/16) the new major doesn't resolve the issue either. So we'll revert for now
Fixes #1234
=> Revert "fix: bump is-wsl to v3 (#1211)"

src/ux/README.md
This PR fixes a typo in `ux/README.md`: the section header `stderr` is duplicated, the second should be `stdout`.
=> fix: typo in ux module README

src/interfaces/parser.ts, src/parser/validate.ts, test/parser/parse.test.ts
Add `atLeastOne` flag property to allow commands to validate that at least one of the specified flags must be provided
Closes #829 
@W-15187594@
=> feat: add atLeastOne flag property

src/interfaces/hooks.ts, src/main.ts
Add `finally` hook that will run at the end of every command execution - regardless of success or failure.
```ts
// src/hooks/finally.ts
import {Hook} from '@oclif/core'
const hook: Hook.Finally = async function (opts) {
this.log(`I finally finished running ${opts.id} with args: ${opts.argv.join(' ')}`)
}
export default hook
```
Closes #1275 
Closes #1263 
Closes #1264
@W-17482601@
=> feat: add finally hook

src/parser/index.ts
The oclif project I am working on includes a features that allow one to orchestrate the execution of a pipeline of Oclif commands. Since it supplies JSON to each command with args and flags it is wasteful to put the json back into a command line and then parse the flags and args out again. That said, we do want to validate the args and flags but now that Oclif better controls is exports, we do not have access to the needed validate function. This PR restores access to the validate call so that we do not have have to copy and reproduce all of that code in our project. We have been working off a private fork for this one change but are nearing release and would like to make things right ahead of that.
Thanks for your consideration!
=> feat: export validate from the Parse module

src/config/config.ts
The `Hook` interface has a handy generic so we can have additional type safety around hook inputs/outputs:
https://github.com/oclif/core/blob/e60d769054b36009743bf39408fe30303e122464/src/interfaces/hooks.ts#L76
This PR extends that logic over to the `config.runHook` method.
=> feat: add generic for extending `Hooks` on `config.runHook`

package.json, src/config/plugin.ts, test/config/fixtures/esm/package.json, test/config/fixtures/mixed-cjs-esm/package.json, test/config/fixtures/mixed-esm-cjs/package.json, test/config/fixtures/typescript/package.json, yarn.lock
Hi!
This PR migrates `globby` to [tinyglobby](https://github.com/SuperchupuDev/tinyglobby), and reducing the total oclif/core dependencies by ~21 (see graphs below)
Tinyglobby has ~52M downloads a month, used by many other large consumers (vite, pnpm, etc) - it has only 2 subdependencies, compared to globby's [23](https://npmgraph.js.org/?q=globby@14.1.0) and fast-glob's [17](https://npmgraph.js.org/?q=fast-glob@3.3.3).
This will reduce the total #deps down by 21 🥳 It's also in-line with the [e18e ecosystem cleanup initative](https://e18e.dev/)
I was looking at oclif's dependency graph https://npmgraph.js.org/?q=%40oclif%2Fcore#select=exact%3Aglobby%4011.1.0 and noticed that globby was being pulled in with it's 23 dependencies, for just one line of usage! 
Compared to after this PR
I've …
=> feat: migrate from globby to tinyglobby

src/interfaces/pjson.ts
Based on https://github.com/oclif/oclif/pull/1784
Adds support to add flags for tarball builds:
```ts
"tarFlags": {
"darwin": "--no-xattrs"
}
```
=> feat: add tar flags config

src/main.ts
Fix regression in 4.5.0 that caused errors to be thrown
Fixes #1424 
Fixes #1423
=> fix: throw errors
