src/command/main.ts
src/config/plugin.ts
src/help/index.ts

From:
https://github.com/oclif/command/commit/90ac07256b3d43577a8db7df0cfadb49e5925a4c
https://github.com/oclif/config/commit/71fb6d9b98bff6c2ccee6961c8afa8403a8b1366
https://github.com/oclif/plugin-help/commit/8957336f3c35675bb243ac90c49c298fbef23e59

fix: support src/command/index cmd

---

package.json
src/command.ts
src/help/index.ts
src/main.ts
test/command/command.test.ts
test/command/main.test.ts

fix: only --version & --help are special global flags

---

src/config/config.ts
src/help/util.ts
src/index.ts
src/interfaces/hooks.ts
src/main.ts
test/help/util.test.ts

Add support for misspelled spaced commands

feat: support misspelled spaced commands

---

src/help/index.ts
src/help/util.ts
src/main.ts
test/help/util.test.ts

Fixes issue with attempting to convert a colon'd command string into spaced command string

fix: conversion of spaced commands to colon commands

---

src/config/config.ts
src/config/plugin.ts
src/flags.ts
src/parser/flags.ts
src/parser/index.ts
src/parser/parse.ts
test/help/format-command.test.ts
test/parser/parse.test.ts

This PR adds two new flag types:
- `url`
@W-9320561@

Add `url` flag

---

src/config/config.ts
src/help/command.ts
src/help/docopts.ts
src/interfaces/help.ts
src/interfaces/parser.ts
test/help/docopts.test.ts
test/help/format-command-with-options.test.ts
test/help/format-command.test.ts
test/helpers/init.js

All of this is adopted from [sfdx](https://github.com/forcedotcom/cli-packages/blob/main/packages/command/src/docOpts.ts) with tweaks to work within oclif.

feat: add docopts

---

package.json
yarn.lock

* Updates `cli-ux` to the newest version that contains some formatting fixes
* Adds `shx` so this can be easily buildable on Windows machines.

chore: update cli-ux

---

src/config/config.ts
src/help/util.ts
src/interfaces/command.ts
test/help/util.test.ts

fix: respect variable args when using spaces

---

src/command.ts
src/config/config.ts
src/help/index.ts
src/interfaces/command.ts
src/interfaces/pjson.ts
test/help/format-command.test.ts

Add a `state` property to the `Command` and `Config` classes to support marking commands and/or plugins as beta

feat: add state property

---

src/command.ts
src/settings.ts
test/help/format-command.test.ts

This flips the default to have --json off

feat: make --json global flag disabled by default

---

src/config/config.ts

Use `Promise.all` to parallelize hooks

feat: parallelize runHook

---

package.json
src/interfaces/parser.ts
src/parser/parse.ts
test/command/main-esm.test.ts
test/command/main.test.ts
yarn.lock

Fixes issues caused by upgrading to typescript@4.5.2
@W-10190107@

fix: resolve typescript compilation errors

---

MIGRATION.md
README.md

Adds a migration guide
@W-10238383@

chore: add migration guide

---

.circleci/config.yml
package.json
test/integration/plugins.e2e.ts
test/integration/sf.e2e.ts
test/integration/util.ts
yarn.lock

Adds integration tests. These tests do the following:
- clone the hello-world repo
- adds well-known plugins to the hello-world CLI
- links the local oclif/core version so that the hello-world CLI and all plugins use that version 
- runs various tests
@W-10328827@

feat: add integration tests

---

src/cli-ux/open.ts

fix: fix default import of lodash

---

src/command.ts

fix: use error type instead of record

---

src/flags.ts
src/interfaces/index.ts
src/parser/flags.ts
src/parser/index.ts
test/parser/parse.test.ts

dir and file flags from https://github.com/salesforcecli/sf-plugins-core/pull/32
original WI: [@W-10766801@](https://gus.lightning.force.com/a07EE00000roHVgYAM)

feat: dir and file flags that validate existence and type

---

src/config/config.ts

fix: set id to alias when adding commands

---

.circleci/config.yml
src/config/config.ts
src/config/plugin.ts
src/interfaces/command.ts
src/interfaces/config.ts
src/interfaces/hooks.ts
src/interfaces/plugin.ts
test/config/config.flexible.test.ts
test/config/config.test.ts

feat: improve Command interface

---

src/help/docopts.ts
src/help/index.ts

Fixes help output for CLIs with a single command

fix: help for single command CLIs

---

src/parser/flags.ts

fix: types on custom flags

---

src/command.ts

fix: remove json flag if subclass overrides enableJsonFlag

---

src/interfaces/parser.ts
src/parser/flags.ts
test/parser/parse.test.ts

fix: more custom flag type overloads

---

package.json
test/help/help-test-utils.ts
test/help/show-customized-help.test.ts
test/help/show-help.test.ts
test/help/util.test.ts
yarn.lock

Updates tests so that we can bump @ocli/test to latest

chore: bump @oclif/test

---

src/interfaces/pjson.ts

adds devDependencies for type safety

feat: pjson interface has devDependencies

---

src/help/docopts.ts

fix: remove brackets for required args

---

src/config/config.ts

fix: set prioritized command to alias

---

src/errors/handle.ts
test/errors/handle.test.ts

Add ability to skip error logging during final error handler
@W-12615284@

feat: add option to skip oclif error printing

---

src/config/config.ts
test/config/config.shell.test.ts

fix: handle undefined env.SHELL on ubuntu tests

---

src/config/config.ts
src/config/plugin.ts
src/help/index.ts
src/interfaces/parser.ts
src/interfaces/plugin.ts
src/parser/parse.ts
src/parser/validate.ts
test/command/command.test.ts
test/help/help-test-utils.ts
test/parser/parse.test.ts

feat: add new param isWritingManifest to Plugin.load

---

src/command.ts
test/command/command.test.ts
test/interfaces/flags.test.ts

fix:  jsonEnabled not handling after pass-through

---

.github/workflows/test.yml
src/config/config.ts
src/interfaces/pjson.ts

@W-13012665@
base for adding `nsisCustomization` pjson key

fix: add nsisCustomization entry

---

src/command.ts

fix: corrected return type for Command.exit

---

src/module-loader.ts

feat: add extensions to esm checking (#694)

---

src/interfaces/pjson.ts

Add `frequency` and `frequencyUnit` to `warn-if-update-available` configuration.

fix: add frequency and frequencyUnit to warn-if-update

---

src/command.ts
src/errors/index.ts
test/command/command.test.ts

Don't throw error on exit code `0`
Closes #660
(Passing tests depend on https://github.com/oclif/core/pull/836)

feat: don't error on exit code 0

---

src/command.ts
src/errors/index.ts
test/command/command.test.ts

fix: restore exit(0) behavior

---

src/help/index.ts

Support `hasDynamicHelp` for v2 commands
@W-14378871@

fix: support hasDynamicHelp for v2 commands

---

yarn.lock

fix mistake: https://github.com/oclif/core/pull/862

fix: change http to https in the lock file

---

src/interfaces/parser.ts
src/parser/parse.ts
test/parser/parse.test.ts

feat: add 'multipleNonGreedy' flag option to assign only one value per multiple flag (#880)

---

package.json
test/command/main.test.ts
yarn.lock

chore: bump plugin-help and plugin-plugins

---

src/interfaces/pjson.ts

Type changes for oclif/oclif#1238, assuming that PR will be accepted.

feat: add node.options to pjson typings

---

package.json

Fixes https://github.com/oclif/oclif/issues/1225#issuecomment-1885627111

fix: make @types/cli-progress a dependency

---

src/cli-ux/prompt.ts

Clear timeout when ux.prompt times out. Fixes failing plugin-not-found unit tests

fix: clear timeout when prompt times out

---

src/parser/errors.ts
src/parser/parse.ts
test/parser/parse.test.ts

fix: show options when required flag or arg is not given a value

---

src/cache.ts

Fixed the error in retrieving the version field.

fix: get core meta version

---

src/interfaces/index.ts

fix: export ArgDefinition

---

package.json
src/config/config.ts
yarn.lock

fix: bump is-wsl to v3

---

src/config/config.ts

This fixes the following issue/example:
- `cli add topic3` is an alias for `cli set topic3`
- `cli add` is an alias for `cli set`
- Try to pipe content to the alias command: `cat foo | cli add topic3`
- The content of `foo` *should* be sent to `cli add topic3`, but it is instead sent to `cli add`
- In contrary, `cat foo | cli set topic3` works fine: the content of `foo` is sent to `cli set topic3` rather than `cli set`
Please let me know if I am missing some context, or if there is a better spot to apply this change. I was looking for a spot to apply it before `Config.load` is called (or at least earlier on than when `loadPluginsAndCommands` is called in `Config.load`) but I couldn't find an appropriate spot

fix: fix aliases in config.commandIDs missing the default topic separator

---

src/ux/index.ts

fix: export action from ux

---

package.json
src/config/plugin.ts
test/config/fixtures/esm/package.json
test/config/fixtures/mixed-cjs-esm/package.json
test/config/fixtures/mixed-esm-cjs/package.json
test/config/fixtures/typescript/package.json
yarn.lock

Merges https://github.com/oclif/core/pull/1363

fix: migrate from globby to tinyglobby (#1363)

---

README.md

docs: update standalone example

---

src/util/cache-command.ts
test/util/cache-command.test.ts

Fixes https://github.com/oclif/plugin-autocomplete/issues/1004
@W-19118139@

fix(W-19118139): standardize aliases
